<a href="https://colab.research.google.com/github/Harikrishnan200/BASICS_OF_ML/blob/main/House_Price_prediction_Multivariable_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv('house.csv')
df.head()

area bedrooms  age   price
0  2600        3   20  550000
1  3000        4   15  565000
2  3200            18  610000
3  3600        3   30  595000
4  4000        5    8  760000

In [4]:
# Here there are missing values in the daraset, so we have t filter it
# Here there is a null value in bedrooms, we have to replace the null value with median of column bedrooms
# Convert the 'bedrooms' column to numeric, handling errors
df['bedrooms'] = pd.to_numeric(df['bedrooms'], errors='coerce')  # The errors='coerce' argument replaces non-convertible values (like empty strings) with NaN (Not a Number).

In [5]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [6]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)  # Fill missing values with the median
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [9]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [10]:
reg.intercept_

383724.9999999998

In [11]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [12]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])